pipeline {

    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nagdeotepooja/SeleniumBDD.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test -Pci'
            }
        }

        stage('Publish Report') {
            steps {
                archiveArtifacts artifacts: 'target/**/*.*', fingerprint: true
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}
